In [ ]:
#numpy -->
#numpy is open-source library of python and its use for scientific calculation.

#why Numpy is better than list ?
# (1).Homogeneous data type
# (1).Less memory consume
# (1).Fast Execution


In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a=[1,45,78,90]
type(a)

list

In [3]:
b=np.array(a)
b

array([ 1, 45, 78, 90])

In [4]:
b.ndim

1

In [5]:
n=[[1,2,3],[4,5,6],[7,8,9]]
n=np.array(n)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
n.ndim # => ndim denote number of dimensions  like in these example
#we have 2 dimension in last two square brackets ']]'

2

In [7]:
n.ndim

2

In [8]:
print("Total Shape: ",n.shape) ##shape=rows,columns
print("Total Elements: ",n.size) ##size=row*column
print("Total Dimension: ",n.ndim) ##ndim-->dimension 1-D(x),2-D(x,y),3-D(x,y,z)

Total Shape:  (3, 3)
Total Elements:  9
Total Dimension:  2


In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr=np.array(arr)
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


How can we create user defined array?

In [10]:
a=[]
size=int(input("Enter total elements"))
for i in range(size):
  val=int(input("Enter elements: "))
  a.append(val)
b=np.array(a)
b

Enter total elements5
Enter elements: 2
Enter elements: 5
Enter elements: 6
Enter elements: 7
Enter elements: 8


array([2, 5, 6, 7, 8])

Pre-defined functions in Numpy

In [11]:
#Matrix---> rows,columns
#Matrix---> Symatric Matrix---> n(r)=n(c) , Asymatric Matrix -->n(r)!=n(c)
#digonal Positional Elements=[(1,1)(2,2),(3,3),(4,4)....(n,n)]

In [12]:
# 1.) zeros()---> It will create an array in which all the values will be 0

In [13]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [14]:
a=np.zeros((3,4))
a


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# 2.). ones()--> It will create an array in which all the values will be 1.

In [16]:
a=np.ones(3)
a

array([1., 1., 1.])

In [17]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 3.) eye()---> It will create an array in which digonal positional elements will be 1
# and rest all will be 0.

In [19]:
a=np.eye(3,3) #symatric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a=np.eye(3,4) #Asymatric matrix
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [21]:
# 4.). diag()---> It will create an array in which we can out custom digonal values

In [22]:
a=np.array([2,90,34,78,56,2])
b=np.diag(a)
b

array([[ 2,  0,  0,  0,  0,  0],
       [ 0, 90,  0,  0,  0,  0],
       [ 0,  0, 34,  0,  0,  0],
       [ 0,  0,  0, 78,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  2]])

In [23]:
# 5.). Random --->
# a). Randint()--> It will generate random numbers in a given range
# syntax: np.random.randint(min_number,max_number,total_numbers)

# b). Rand() --> It will generate random numbers from 0 to 1
#Syntax: np.random.rand(total_numbers)

In [24]:
a=np.random.randint(1,10,3)
a

array([3, 8, 3])

In [25]:
b=np.random.rand(5)
b

array([0.55110878, 0.59656709, 0.6727041 , 0.20684926, 0.56307154])

In [26]:
import numpy as np

In [27]:
## Seed function => seed()-> For fix the random number, we will use seed()


In [28]:
#Example of seed()..

np.random.seed()
a=np.random.randint(1,10,3)
a

array([1, 2, 5])

# Reshape The Array
# n(rows) * n(columns) = n(total_elements) <= This is method of reshaping the array..


In [29]:
import numpy as np

In [30]:
# Examples of reshaping the array..

a=np.random.randint(1,50,12)
a

array([29, 29,  5, 35, 17, 15, 25,  7, 44, 23, 28,  7])

In [31]:
a.shape

(12,)

In [32]:
# reshape methods kaise kaise yeh 12 elements reshape ho sakte hain..
# 1*12 , 12*1
# 2*6  , 6*2
# 3*4  , 4*3

In [33]:
a.reshape(2,6) #here reshape elements like here 2 rows and 6 columns in array..


array([[29, 29,  5, 35, 17, 15],
       [25,  7, 44, 23, 28,  7]])

In [34]:
a.reshape(3,4)

array([[29, 29,  5, 35],
       [17, 15, 25,  7],
       [44, 23, 28,  7]])

In [35]:
a.reshape(4,3)

array([[29, 29,  5],
       [35, 17, 15],
       [25,  7, 44],
       [23, 28,  7]])

Conditional Selection in Numpy -:

In [36]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [38]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [39]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [40]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [41]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [42]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [43]:
a+b

array([[ 6,  8],
       [10, 12]])

In [44]:
a-b

array([[-4, -4],
       [-4, -4]])

In [45]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [46]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [47]:
import numpy as np

In [48]:
#Linespace()-> It will return the values with same gap numbers..


In [49]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [50]:
#Unique()=> It will return 3 arrays.
# 1.) arr=> It will return array in which we have unique values
# 2.) return_index= True => Unique value indexing
# 3.) return_counts= True => It will frequency of each unique value



In [51]:
a=np.array([10,20,10,10,10,10,20,30,40,40,30,10,10,10,50])
np.unique(a,return_index=True,return_counts=True)


(array([10, 20, 30, 40, 50]),
 array([ 0,  1,  7,  8, 14]),
 array([8, 2, 2, 2, 1]))